stages:
  - deploy

variables:
  CHART_PATH: ./charts/mongodb
  
  STAGE_NAMESPACE: staging
  PROD_NAMESPACE: prod
  STAGE_RELEASE_NAME: raddit-stage-mongodb
  PROD_RELEASE_NAME: raddit-prod-mongodb


# deploy to staging environment
deploy_staging:
  stage: deploy
  image: victorfrag/docker-helm:v2.14.3
  before_script:
    - helm init --client-only
  script:
    - helm upgrade --install
      --wait
      --namespace=${STAGE_NAMESPACE}
      ${STAGE_RELEASE_NAME} ${CHART_PATH}
  environment:
    name: staging
  only:
  - master

# deploy to production environment (manual)
deploy_prod:
  stage: deploy
  image: victorfrag/docker-helm:v2.14.3
  before_script:
    - helm init --client-only
  script:
    - helm upgrade --install
      --wait
      --namespace=${PROD_NAMESPACE}
      ${PROD_RELEASE_NAME} ${CHART_PATH}
  environment:
    name: production
  when: manual
  only:
  - master
